FROM alpine:3.3

MAINTAINER nizq <ni.zhiqiang@gmail.com>

RUN echo "===> Adding dependency..." && \
    apk add --update zlib openssl libstdc++ libpcap geoip libgcc && \
    rm -rf /var/cache/apk/*

ADD bro.tar.gz /

VOLUME ["/data/logs", "/data/config"]
WORKDIR /data/logs

ENTRYPOINT [ "/usr/local/bin/bro" ]
