FROM alpine:3.4

MAINTAINER nizq <ni.zhiqiang@gmail.com>

RUN echo "===> Adding dependency..." && \
    apk add --update zlib openssl libstdc++ libpcap geoip libgcc && \
    rm -rf /var/cache/apk/*

ADD bro.tar.gz /

VOLUME ["/data/logs", "/data/config"]
WORKDIR /data/logs

ENV BROPATH .:/data/config:/usr/local/share/bro:/usr/local/share/bro/policy:/usr/local/share/bro/site

ENTRYPOINT [ "/usr/local/bin/bro" ]
CMD [ "-h" ]
